name: build-windows-exe
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pyinstaller
      - name: Build GUI exe
        run: pyinstaller --onefile --noconsole --name LeeCFDI --collect-all pandas --collect-all openpyxl leecfdi_gui.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LeeCFDI-windows-exe
          path: dist/LeeCFDI.exe
